- hosts: all
  become: true
  become_user: root
  pre_tasks:
    - name: Apt | update cache
      apt: update_cache=yes cache_valid_time=3600
  tasks:
    - include: golang.yml
      vars:
        version: 1.7.5
        sha256sum: 2e4dd6c44f0693bef4e7b46cc701513d74c3cc44f2419bf519d7868b12931ac3
    - include: golang.yml
      vars:
        default: yes
        version: 1.8
        sha256sum: 53ab94104ee3923e228a2cb2116e5e462ad3ebaeea06ff04463479d7f12d27ca
    - include: erlang.yml otp_version=19.3 elixir_version=1.4.1-1
    - include: python.yml version=2.7.13 executable=python2.7 easy_install_version=2.7
    - include: python.yml version=3.6.1 executable=python3.6 easy_install_version=3.6
    - include: git.yml
  vars:
    user_name: Scott Moynes
    user_email: scott.moynes@gmail.com
